### ISSUE TITLE
Readme erstellen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#1]
Ein Readme mit einer Anleitung für den Download muss erstellt werden

**Comment by mariusmaass** [comment]
Was genau ist damit gemeint? 
Wozu ist das Readme? 
Für die Datenbanken oder für etwas anderes?^^
Wenn etwas anderes dann was?

**Comment by BenSchumacher-HU** [comment]
In einem Readme wird festgelegt, wir man das Projekt installieren kann und welche Pakete benötigt werden. Zudem wird dort beschrieben, wie man das Projekt und die Tests dazu startet.
In eurem Fall kommt noch dazu, dass die Installation der Datenbank beschrieben werden soll.
Ein (recht umfangreiches) Beispiel ist [hier](https://gist.github.com/jxson/1784669) zu finden

**Comment by BenSchumacher-HU** [comment]
@MasterOfDesaster Wer kümmert sich darum?

**Comment by BenSchumacher-HU** [comment]
Man kann sich auch das Readme der Middleware [angucken](https://github.com/hu-semesterprojekt-genombrowser/Alazen-Middleware/blob/master/README.md)

**Comment by MasterOfDesaster** [comment]
So, sollte jetzt hoffentlich zur Zufriedenheit fertig sein.
