### ISSUE TITLE
Nullpointer exception in GParser

### ISSUE THREAD

**Issue by KacperSiedlecki** [hu-semesterprojekt-genombrowser/Alazen-Integration#12]
Bitte bearbeiten, sonst kann nicht testen.

java.lang.NullPointerException
	at GParser.writeDataTabel(GParser.java:682)
	at GParser.troubleProtocol(GParser.java:2004)
	at GParser.parse(GParser.java:817)
	at YAP.Es_Funktioniert(YAP.java:511)
	at YAP.main(YAP.java:542)

**Comment by mariusmaass** [comment]
gib mir ein File zum testen. Nur die Nullpointerwurfstelle bring mir nicht da ist ein Fehler im inputfile der nicht erkannt wird, und das läuft dann durch zum writer und der sagt dann hey das geht nicht und bumm alles kaputt. Natürlich versagt hier mein test aber du kannst hier nicht einfach sagen mach mal was.

**Comment by KacperSiedlecki** [comment]
Lade Dateien runter (Yap.java, GParser.java und Download.java) compiliere
die, fuehre YAP aus und dann liegen irgendwo im Ordner Dateien). du kriegst
immer .info Datei, also wird's die sein. Die per Mail zu schicken waere zu
problematisch, ist zu gross.

Am 23. Januar 2016 um 13:38 schrieb mariusmaass <notifications@github.com>:

**Comment by mariusmaass** [comment]
soo Kacper das Problem ist/war das dein Format nicht stimmt. erwartet wurde SampleID aber gefunden wird $$ du musst das $$ das du schreibst wenn du die sachen in zeile 111 strB.append("#");
	strB.append(System.getProperty("line.separator"));
	strB.append("$$");
	strB.append(System.getProperty("line.separator"));
	hier weglöschst sollte es durchlaufen.

**Comment by mariusmaass** [comment]
warte einfach in zeile 111 im LParser
strB.append("#");
	strB.append(System.getProperty("line.separator"));
	strB.append("$$");
	strB.append(System.getProperty("line.separator"));
	entfernen. Dann akzeptiert er

**Comment by KacperSiedlecki** [comment]
Ich habe es gefixt.
