### ISSUE TITLE
Dateistruktur überarbeiten

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#14]
Die Struktur der Datein im Repro soll neu organisiert werden.
* ~~Die Sourcefiles sollen in einen `src/` Ordner.~~
* ~~Wofür wird der Ordner `Daten` benötigt?~~
* Bei ein paar Datein ist aus dem Dateinamen nicht ersichtlich, was der Inhalt ist z.b. `panel.txt` ist.
* Die gesamten "zusätzlichen" Dateien, wie `allowedReference.txt` sollten auch in einen passenden Ordner

**Comment by BenSchumacher-HU** [comment]
Gute Idee mit dem Verschieben Marius, aber jetzt liegen Dateien doppelt vor :wink:

**Comment by mariusmaass** [comment]
sooo ich denk mal dem ist genuege getan.
Das mit den Datennamen liegt ja daran das es echte daten sind und die natuerlich nicht sinnvoll umzubenennen sind und die liegen jetzt ja auch in einem Testordner.

**Comment by BenSchumacher-HU** [comment]
:+1:
