### ISSUE TITLE
Code des 1kParsers überarbeiten

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#15]
In dem Code muss folgendes angepasst werden:
* Klassenname ändern: Dabei soll ein sprechender Name gewählt werden, wie z.b. ThousandGenomeParser
* Das Hühnchen muss weg.
* Wie besprochen, soll das Sigelton Pattern verwendet werden.
* Das Interface muss noch implementiert werden. Dabei kann dann auch `Es_Funktioniert()` umbenannt werden
* Ein paar Variablennamen müssen noch angepasst werden. Z.B. ist in Zeile 181<br>
```int I_Variable1=0;``` das wenig aussagekräftig
* Die Kommentierung ist gut und brauch nicht verbessert werden

**Comment by KacperSiedlecki** [comment]
Jetzt in Ordnung?

**Comment by BenSchumacher-HU** [comment]
Gute Idee, dass in eine eigene Klasse auszulagern. Alles klar :+1:

**Comment by BenSchumacher-HU** [comment]
Stimmen die drei Testfälle in der Testklasse? Die habe dich übrigens umbenannt, damit die einheitlich benannt werden

**Comment by KacperSiedlecki** [comment]
Eee, Testfaelle? Musst du Marius fragen der hat sich darum gekuemmert.

**Comment by BenSchumacher-HU** [comment]
@mariusmaass : Kannst du dir das bitte mal angucken
