### ISSUE TITLE
Klassennamen von dbSNP_Parser ändern

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#16]
Der Klassennamen vom dbSNP Parser muss geändert werden, da er mit einem Großbuchstaben beginnen muss. Ich würde schlage DBSNPParser vorschlagen

**Comment by fscholze** [comment]
erledigt. 
Und hast du ein bug gefunden oder die Klassenbenennung als "bug"?

**Comment by BenSchumacher-HU** [comment]
Ich meinte die Benennung als Bug. Kannst du noch bitte den _ aus den Namen entfernen? Der Rest ist gut

**Comment by BenSchumacher-HU** [comment]
Alles fertig :+1:
