### ISSUE TITLE
Commit ueberschrieben

### ISSUE THREAD

**Issue by KacperSiedlecki** [hu-semesterprojekt-genombrowser/Alazen-Integration#17]
Ich habe glaube ich den commit 93dd39d686503c84b5903f7441b158aa9a71a3db ueberschrieben. Sorry, tut mir leid, war keine Absicht...

**Comment by BenSchumacher-HU** [comment]
Kein Ding. So wichtig war das auch nicht :smile:

**Comment by BenSchumacher-HU** [comment]
Mit  555565 neu gemacht
