### ISSUE TITLE
Ant File anpassen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#2]
Das Antfile muss angepasst werden, damit der Build u.a. auch durch Travis CI funktioniert. Am besten für jeden Test eine eigene Klasse mit nur einer Main Methode.
Dabei muss folgendes eingebaut werden:
* ~~Für die main.java die .class Datein erstellen und daraus ein jar. bauen~~
* ~~Die Mainklasse laufen lasse~~
* ~~Die Testklassen bauen~~
* ~~Die Testklassen laufen lassen~~
* ~~Die Dokumentation erstellen~~

Eine Einführung in Ant findet man [hier](https://ant.apache.org/manual/using.html).
Zum Bauen der Dokumentation findest man [hier](https://ant.apache.org/manual/Tasks/javadoc.html) Informationen.

**Comment by mariusmaass** [comment]
Weil ich ja keine Antwort per mail bekomme hier noch einmal^^ Also sollen die Testklassen mit dem ant Dafault laufen oder haben sie ihren eigenen ansprungpunkt also sowas wie ant test? Ach und soweit ich das antfile hier ueberblicke wird doch die main auch gestartet oder ? also wäre der punkt doch auch schon weg.

**Comment by BenSchumacher-HU** [comment]
Am besten haben die Tests ein eigenes Target. Ja, in dem Ant File wird auch die Main (bzw. die Mains) festgelegt.

**Comment by BenSchumacher-HU** [comment]
Nachtrag: Ja, die Main.Java wird schon gebaut und ausgeführt.

**Comment by BenSchumacher-HU** [comment]
Alles super :+1:
