### ISSUE TITLE
copyThread überarbeiten

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#20]
Zwei kleine Änderungen müssen noch vorgenommen werden:
* ~~Der Klassenname sollte groß geschrieben werden~~
* Bei der Dokumentation  fehlen noch ein paar Angaben

**Comment by BenSchumacher-HU** [comment]
Willst du das nicht als Klasse implementieren statt alles auf static zu setzen?

**Comment by BenSchumacher-HU** [comment]
@MasterOfDesaster Kannst du das eben fertig machen? Dann sind alle Issues erledigt

**Comment by MasterOfDesaster** [comment]
So, hoffe das ist in Ordnung so.

**Comment by BenSchumacher-HU** [comment]
Jup :+1:
