### ISSUE TITLE
DBSNPParserTest fixen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#23]
@fscholze @SB61 Der Test 

     assertTrue(gParser.parse("Testdaten/dbSNP.txt")); 

des DBSNPParserTest schlägt fehl. Guckt ihr euch das mal bitte an

**Comment by BenSchumacher-HU** [comment]
Der GParser meldet:
`
Der Test ob die Phrase SampleID: in Zeile 1354 enthalten ist, ist negativ ausgefallen, da der : fehlt.
ueberpruefen sie ihr Format.
`

**Comment by SB61** [comment]
Wo liegt denn die Datei? Denn ich habe bei der im Alazan-Integration Ordner keinen Fehler in der Zeile gefunden.

**Comment by BenSchumacher-HU** [comment]
Der Parser parst ja `Testdaten/TestVCF.txt`und erzeugt `Testdaten/TestVCF_out.txt`. Dies wird dann vom GParser geparst. Dabei findet dieser einen Fehler in Zeile 1354, obwohl die Datei nur 1352 Zeilen hat. 
Lass mal bei dir `ant runTest` laufen und guck was passiert

**Comment by fscholze** [comment]
Zutat von Marius:
"soo also ich versteh das jetzt nicht den bei mir läuft alles es gibt kein Falschen output wo wurde das wie getestet?
da gibts doch nur probleme wenn da ne hashmapdatei ist."

Wo hast du es denn getestet?

Von meinem iPhone gesendet

**Comment by BenSchumacher-HU** [comment]
Unter [https://github.com/hu-semesterprojekt-genombrowser/Alazen-Integration/blob/fix/dbnsp_parser/Testdaten/TestVCF_out.txt] findet ihr die aus `TestVCF.txt` erzeugte Datei. Könnt ihr die mit dem GParser parsen?

**Comment by fscholze** [comment]
@BenSchumacher-HU könntest du dich bitte an @mariusmaass  wenden? Er hat ja den GParser gemacht und mir gesagt auch das Testfile von dir läuft ohne Probleme durch. Nur dass da keine initialHashmap.txt rumliegen darf. Also als participants noch Marius adden.

**Comment by mariusmaass** [comment]
also ich glaube jetzt zu wissen was passiert ist. Also alle testdateien wurden nacheinander ausgefuehrt. Dabei ist beim 1000GenomParserTest eine initialHashmap.txt erstellt worden. Darin werden die Namen von Sampels gespeichert. Da nun aber das angegebene vcf NICHT das format von 1000Genom erfuellt sondern NUR das von DBSNP kam es zu Abbruch von diesem Test. Das Problem: nun war die initialHashmap.txt noch da und deshalb wurde ein anderer Test als sonst verwendet und dieses Format erfuellt das Inputfile aus dem DBSNPParser nicht mehr. Ist nur eine Vermutung aber das es so im 1000GenomTest stand und ich so einen aehnlichen Fehler bekommen hab. Wenn es das nicht war haette ich gerne eine Detaliertere Aussage und alle files vor allem das Errorfile.

**Comment by mariusmaass** [comment]
soo aber das war auch mein fehler weil ich vergessen hab die test.vcf hochzuladen.

**Comment by BenSchumacher-HU** [comment]
Mit aef71555d542eb52ed794682a26754c48a68318a gefixt
