### ISSUE TITLE
Klasse Download

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#24]
Wo für wird diese Klasse benötigt? Kann sie nicht auch in YAP.java mit integriert werden? Wenn sie als eigenständige Klasse bleiben soll, fehlt noch die Dokumentation und YAP sollte eine Instanz davon als Parameter bekommen

**Comment by KacperSiedlecki** [comment]
Ich habe Kommentierung ergänzt (irgendwie lag es nur auf meinem Rechner kommentiert, habe's wahrscheinlich vergessen hochzuladen). Ich werde den Programm aber jetzt nicht ändern wenn es nicht wegen eines bugs ist, das ganze wurde schon getestet und Ich (und wahrscheinlich andere aus meiner Gruppe auch) habe keine Lust kurz vor der Präsentation nicht notwendigen Änderungen vorzunehmen die vielleicht zu Problemen führen können. Es ist einfach zu spät dafür, der Code sollte vor paar Wochen fertig sein und jetzt ist einfach zu spät.

**Comment by MasterOfDesaster** [comment]
Die Betreuer hatten bei dem letzten Codereview auch nichts dadran auszusetzen, unser Code läuft jetzt so, wie er steht, es ist kein Fehler drin, nichts.
Eine letzte, überstürzte Änderung wird möglicherweise nur Bugs in unser, derzeitig, funktionierendes Programm reinschießen, was mMn nicht wirklich sinnvoll ist. Ist doch schön, wenn es derzeit endlich funktioniert, da sollte man nicht wegen solcher Kleinigkeiten was riskieren, finde ich...

**Comment by BenSchumacher-HU** [comment]
Dann lassen wir das als Klasse so stehen
