### ISSUE TITLE
Methode Parse in GParser

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#25]
Warum wird die Methode parse drei mal als public benötigt? Ist nicht die einzige, die public sein muss, die mit vier Parametern?

**Comment by BenSchumacher-HU** [comment]
Antwort von @Martin-Bauer 
Hi Ben,

es ist ganz einfach. Ich hab hier die Möglichkeit offengelassen welche zu verwenden sei, aber da alle parse(String)
verwenden hab ich das offengelassen. von daher wäre es ziemlich schlecht parse(String) auf private zu setzten.
darum auch drei methoden. Will man jetzt mit GParser ein Inputfile parsen kann man dann halt die Pfade angegen und sich selbst entscheiden was man nimmt.

**Comment by BenSchumacher-HU** [comment]
Hi Marius,
Wenn alle nur parser(String) verwenden, warum braucht man dann die anderen beiden Methoden?

**Comment by mariusmaass** [comment]
Wie gesagt man braucht sie nicht sie sind aber nützlich und ob ich jetzt 10 20 30 Zeilen mehr im code stehen hab, dürfte doch keinen interessieren oder kann ich dank java irgendwelche systemdateien überschreiben und deswegen wären die ein sicherheitrisiko

**Comment by BenSchumacher-HU** [comment]
Dann lassen wir es drin
