### ISSUE TITLE
1000 Genome Project Parser beenden

### ISSUE THREAD

**Issue by MasterOfDesaster** [hu-semesterprojekt-genombrowser/Alazen-Integration#4]

**Comment by KacperSiedlecki** [comment]
?

**Comment by KacperSiedlecki** [comment]
Ist fertig, also funktioniert.

**Comment by BenSchumacher-HU** [comment]
Kacper, wenn der Code komplett fertig, ist erstellt bitte eine Pull Request zu master. Dann können alle in diesem Pull Request ihr Feedback zum Code abgeben. Wenn der Pull Requet angenommen ist, kann der Issue geschlossen werden.
