### ISSUE TITLE
dbSNP Parser beenden

### ISSUE THREAD

**Issue by MasterOfDesaster** [hu-semesterprojekt-genombrowser/Alazen-Integration#5]

**Comment by BenSchumacher-HU** [comment]
Felix, wenn der Code komplett fertig, ist erstellt bitte eine Pull Request zu master. Dann können alle in diesem Pull Request ihr Feedback zum Code abgeben. Wenn der Pull Requet angenommen ist, kann der Issue geschlossen werden. (siehe auch #4 )
