### ISSUE TITLE
Umlaute aus dem GParser entfernen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#6]
Die Umlaute aus GParser.java müssen entfernt werden, um Kompatibilität mit Travis zu gewährleisten. s.a. [hier](https://travis-ci.org/hu-semesterprojekt-genombrowser/Alazen-Integration)

**Comment by mariusmaass** [comment]
Ich hoffe doch sie sind weg ansonsten sind es Umlaute wie ß oder ê oder oder oder

**Comment by BenSchumacher-HU** [comment]
Falsche Zeichen gibt es noch:
* GParser.java:21
* main.java:156
* main.java:199

**Comment by BenSchumacher-HU** [comment]
Closed: Umlaut in main.java mit 3151cc6 gefixt
