### ISSUE TITLE
Prüfung des LParsers

### ISSUE THREAD

**Issue by KacperSiedlecki** [hu-semesterprojekt-genombrowser/Alazen-Integration#7]
Kannst du mal schauen ob, die Dateien die LParser rausgibt von GParser akzeptiert werden?

**Comment by mariusmaass** [comment]
Bin ja wie in der mail steht schon dabei

**Comment by KacperSiedlecki** [comment]
funktioniert es jetzt?

**Comment by mariusmaass** [comment]
Sollte funktionieren
